import {StyleSheet} from "react-native";

export default StyleSheet.create({
    button: {
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        padding: 20,
        margin: 0,
        borderColor: "gray",
        borderWidth: 1,
        backgroundColor: "#eaeaea",
    },
    buttonQuestion: {
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        padding: 10,
        margin: 0,
        borderColor: "gray",
        borderWidth: 1,
        backgroundColor: "#eaeaea",
    },
    question: {
        flexDirection: "row",
        justifyContent: "space-between",
        textAlign: "left",
        padding: 20,
        margin: 0,
        backgroundColor: "#eaeaea",
        fontFamily: "Gill Sans",
    },
    container: {
        padding: 20,
        marginTop: 0,
        backgroundColor: "#e0e0e0",
        alignItems: "center",
        borderWidth: 1,
    },
    container2: {
        padding: 18,
        marginTop: 0,
        backgroundColor: "#f5f5f5",
        alignItems: "center",
        borderWidth: 1,
    },
    textTags2: {fontSize: 22, fontFamily: "Gill Sans"},
    textTags: {fontSize: 18, fontFamily: "Gill Sans"},
    textButton: {fontSize: 20, textAlign: "center", fontFamily: "Gill Sans"},
    background: {
        flex: 1,
        backgroundColor: "#eaeaea",
        flexDirection: "column",
    },
    backgroundStart: {
        flex: 1,
        backgroundColor: "#4e4d4d",
        flexDirection: "column",
    },
});
